### ISSUE TITLE
Migration to MapLibre GL

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames-assen#2]
Since Mapbox decision to release version 2.0 of Mapbox GL under closed-source license, I have decided to migrate to MapLibre GL (fork of Mapbox GL).

At first sight, it seems that only the CSS needs to be updated (see https://github.com/openknowledgebe/equalstreetnames-brussels/commit/81c2dfefd2917b7fb6e100f74b5f13d2f872a172, for instance)

**Comment by RobinLinde** [comment]
Should now be fixed by commits https://github.com/RobinLinde/equalstreetnames-assen/commit/b8b3e48fdd39b2b2402e87c1c81e0339c6437939 and https://github.com/RobinLinde/equalstreetnames/commit/2de26f69f4d9b43e31d928e3e766d8a4c6620767.

**Comment by RobinLinde** [comment]
Opened pull request https://github.com/openknowledgebe/equalstreetnames/pull/121
